### ISSUE TITLE
test the issue高级用法

### ISSUE THREAD

**Issue by 4amup** [wozhizui/wozhizui.github.io#1]
* [基于GitHub的敏捷学习方法](http://insights.thoughtworkers.org/agile-learning-method-base-on-github/)
* [《搞定》最佳实践：如何利用滴答清单（TickTick）实践 GTD 理念？](https://blog.jimmylv.info/2017-02-20-gtd-best-practice-137/)

**Comment by wozhizui** [comment]
！#test3

**Comment by wozhizui** [comment]
#！试试在评论中直接利用"#!"新建issue

**Comment by 4amup** [comment]
#! 试试直接使用“#!”在commit中新建issue

**Comment by 4amup** [comment]
测试一下评论功能
